# This is a basic workflow to help you get started with Actions

name: Bootcamp 2020

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 13
      - name: Prepare for Yarn Installation
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
      - name: Deploy Using Surge
        run: surge ./build grubby-silver.surge.sh --token ${{secrets.SURGETOKEN}}
        
